# Generated by Django 5.0.7 on 2024-08-16 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_pagina_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
